use std::fmt;

use crate::error::ConfigError;
use crate::value::ConfigValue;

/// A custom deserializer function signature for fields like `Duration`.
/// Takes the raw `ConfigValue` and field metadata, returns a transformed `ConfigValue`.
pub type DeserializeFn = fn(&ConfigValue, &FieldMeta) -> Result<ConfigValue, ConfigError>;

/// Metadata for one config field, generated by `#[derive(Config)]`.
/// This is what the resolver works with; users never construct it directly.
#[derive(Debug, Clone)]
pub struct FieldMeta {
    /// Field name as it appears in the struct (e.g. `"redis_host"`).
    pub name: &'static str,
    /// Dotted config ID path used in files (e.g. `"redis.host"`).
    pub config_key: &'static str,
    /// Environment variable name (e.g. `"RUSTVELLO__REDIS__HOST"`).
    pub env_key: &'static str,
    /// Generic (no group) environment variable name (e.g. `"RUSTVELLO__HOST"`).
    ///
    /// Used as a fallback when the class-specific `env_key` is not set.
    /// This matches Python cistell behavior where `PREFIX__FIELDNAME` is
    /// checked when `PREFIX__CLASSNAME__FIELDNAME` is absent.
    /// `None` when a custom `env_key` is specified.
    pub generic_env_key: Option<&'static str>,
    /// Whether this field is secret (never printed).
    pub is_secret: bool,
    /// Human-readable expected type (e.g. `"u16"`, `"String"`) — for error messages.
    pub expected_type: &'static str,
    /// Whether the field has a default value (required if `false`).
    pub has_default: bool,
    /// Optional custom deserializer function for types like `Duration`.
    /// When set, the resolver calls this instead of `ConfigValue::coerce::<T>()`.
    pub deserialize_fn: Option<DeserializeFn>,
}

/// Wraps a config value that must never appear in logs, debug output, or displays.
///
/// `Secret<T>` intentionally implements `Debug` and `Display` as `<secret>`.
/// The actual value is only accessible via `.expose()`.
///
/// ### Memory safety
/// When `T: zeroize::Zeroize`, the inner value is zeroed on `Drop`.
/// This prevents secrets lingering in freed memory (heap inspection, core dumps).
///
/// ### Feature gates
/// - `serde`: enables `Serialize` (always `"<secret>"`) and `Deserialize` (transparent)
/// - `zeroize`: enables `Zeroize + ZeroizeOnDrop` for `Secret<T>` where `T: Zeroize`
#[derive(Clone)]
pub struct Secret<T>(T);

impl<T> Secret<T> {
    pub fn new(value: T) -> Self {
        Self(value)
    }

    /// The ONLY way to access the inner value.
    /// Call sites are easy to audit: `grep` for `.expose()`.
    pub fn expose(&self) -> &T {
        &self.0
    }

    pub fn into_inner(self) -> T {
        self.0
    }
}

/// Ergonomic construction: `Secret::from("hunter2")`
impl<T> From<T> for Secret<T> {
    fn from(value: T) -> Self {
        Self(value)
    }
}

/// Two secrets are equal if their inner values are equal.
/// Note: this is NOT constant-time comparison. For cryptographic
/// use cases, wrap a type that implements constant-time `PartialEq`.
impl<T: PartialEq> PartialEq for Secret<T> {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<T: Eq> Eq for Secret<T> {}

/// Default delegates to inner type's Default.
impl<T: Default> Default for Secret<T> {
    fn default() -> Self {
        Self(T::default())
    }
}

/// Print `<secret>` — never the actual value.
impl<T> fmt::Debug for Secret<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "<secret>")
    }
}

impl<T> fmt::Display for Secret<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "<secret>")
    }
}

/// Serializing a Secret always writes the string `"<secret>"` — not the value.
#[cfg(feature = "serde")]
impl<T> ::serde::Serialize for Secret<T> {
    fn serialize<S: ::serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str("<secret>")
    }
}

#[cfg(feature = "serde")]
impl<'de, T: ::serde::Deserialize<'de>> ::serde::Deserialize<'de> for Secret<T> {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        T::deserialize(deserializer).map(Secret)
    }
}

/// Implement `Zeroize` for `Secret<T>` where `T: Zeroize`.
/// Users can call `.zeroize()` to scrub the inner value from memory.
#[cfg(feature = "zeroize")]
impl<T: ::zeroize::Zeroize> ::zeroize::Zeroize for Secret<T> {
    fn zeroize(&mut self) {
        self.0.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_secret_debug_redacts() {
        let s = Secret::new("hunter2");
        assert_eq!(format!("{s:?}"), "<secret>");
    }

    #[test]
    fn test_secret_display_redacts() {
        let s = Secret::new("hunter2");
        assert_eq!(format!("{s}"), "<secret>");
    }

    #[test]
    fn test_secret_expose() {
        let s = Secret::new(42_u32);
        assert_eq!(*s.expose(), 42);
    }

    #[test]
    fn test_secret_into_inner() {
        let s = Secret::new("hello".to_owned());
        let inner = s.into_inner();
        assert_eq!(inner, "hello");
    }

    #[test]
    fn test_secret_from() {
        let s: Secret<&str> = Secret::from("val");
        assert_eq!(*s.expose(), "val");
    }

    #[test]
    fn test_secret_partial_eq() {
        assert_eq!(Secret::new("a"), Secret::new("a"));
        assert_ne!(Secret::new("a"), Secret::new("b"));
    }

    #[test]
    fn test_secret_default() {
        let s = Secret::<String>::default();
        assert_eq!(s.expose(), "");
    }

    #[test]
    fn test_secret_clone() {
        let s = Secret::new("cloned".to_owned());
        let c = s.clone();
        assert_eq!(*c.expose(), "cloned");
    }

    #[cfg(feature = "serde")]
    #[test]
    fn test_secret_serde_serialize() {
        let s = Secret::new("hunter2".to_owned());
        let json = serde_json::to_string(&s).unwrap();
        assert_eq!(json, r#""<secret>""#);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn test_secret_serde_deserialize() {
        let s: Secret<String> = serde_json::from_str(r#""actual_value""#).unwrap();
        assert_eq!(s.expose(), "actual_value");
    }
}
